# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401
from swagger_server.models.inline_response200_classification import InlineResponse200Classification
from swagger_server.models.inline_response200_detection import InlineResponse200Detection

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, query_id: str=None, classification: InlineResponse200Classification=None, detection: InlineResponse200Detection=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param query_id: The query_id of this InlineResponse200.  # noqa: E501
        :type query_id: str
        :param classification: The classification of this InlineResponse200.  # noqa: E501
        :type classification: InlineResponse200Classification
        :param detection: The detection of this InlineResponse200.  # noqa: E501
        :type detection: InlineResponse200Detection
        """
        self.swagger_types = {
            'query_id': str,
            'classification': InlineResponse200Classification,
            'detection': InlineResponse200Detection
        }

        self.attribute_map = {
            'query_id': 'query_id',
            'classification': 'classification',
            'detection': 'detection'
        }

        self._query_id = query_id
        self._classification = classification
        self._detection = detection

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def query_id(self) -> str:
        """Gets the query_id of this InlineResponse200.


        :return: The query_id of this InlineResponse200.
        :rtype: str
        """
        return self._query_id

    @query_id.setter
    def query_id(self, query_id: str):
        """Sets the query_id of this InlineResponse200.


        :param query_id: The query_id of this InlineResponse200.
        :type query_id: str
        """

        self._query_id = query_id

    @property
    def classification(self) -> InlineResponse200Classification:
        """Gets the classification of this InlineResponse200.


        :return: The classification of this InlineResponse200.
        :rtype: InlineResponse200Classification
        """
        return self._classification

    @classification.setter
    def classification(self, classification: InlineResponse200Classification):
        """Sets the classification of this InlineResponse200.


        :param classification: The classification of this InlineResponse200.
        :type classification: InlineResponse200Classification
        """

        self._classification = classification

    @property
    def detection(self) -> InlineResponse200Detection:
        """Gets the detection of this InlineResponse200.


        :return: The detection of this InlineResponse200.
        :rtype: InlineResponse200Detection
        """
        return self._detection

    @detection.setter
    def detection(self, detection: InlineResponse200Detection):
        """Sets the detection of this InlineResponse200.


        :param detection: The detection of this InlineResponse200.
        :type detection: InlineResponse200Detection
        """

        self._detection = detection
