# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200Detection(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, performed: bool=None, duration: int=None, detection_results: List[List[object]]=None):  # noqa: E501
        """InlineResponse200Detection - a model defined in Swagger

        :param performed: The performed of this InlineResponse200Detection.  # noqa: E501
        :type performed: bool
        :param duration: The duration of this InlineResponse200Detection.  # noqa: E501
        :type duration: int
        :param detection_results: The detection_results of this InlineResponse200Detection.  # noqa: E501
        :type detection_results: List[List[object]]
        """
        self.swagger_types = {
            'performed': bool,
            'duration': int,
            'detection_results': List[List[object]]
        }

        self.attribute_map = {
            'performed': 'performed',
            'duration': 'duration',
            'detection_results': 'detection_results'
        }

        self._performed = performed
        self._duration = duration
        self._detection_results = detection_results

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Detection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_detection of this InlineResponse200Detection.  # noqa: E501
        :rtype: InlineResponse200Detection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def performed(self) -> bool:
        """Gets the performed of this InlineResponse200Detection.


        :return: The performed of this InlineResponse200Detection.
        :rtype: bool
        """
        return self._performed

    @performed.setter
    def performed(self, performed: bool):
        """Sets the performed of this InlineResponse200Detection.


        :param performed: The performed of this InlineResponse200Detection.
        :type performed: bool
        """

        self._performed = performed

    @property
    def duration(self) -> int:
        """Gets the duration of this InlineResponse200Detection.


        :return: The duration of this InlineResponse200Detection.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration: int):
        """Sets the duration of this InlineResponse200Detection.


        :param duration: The duration of this InlineResponse200Detection.
        :type duration: int
        """

        self._duration = duration

    @property
    def detection_results(self) -> List[List[object]]:
        """Gets the detection_results of this InlineResponse200Detection.


        :return: The detection_results of this InlineResponse200Detection.
        :rtype: List[List[object]]
        """
        return self._detection_results

    @detection_results.setter
    def detection_results(self, detection_results: List[List[object]]):
        """Sets the detection_results of this InlineResponse200Detection.


        :param detection_results: The detection_results of this InlineResponse200Detection.
        :type detection_results: List[List[object]]
        """

        self._detection_results = detection_results
