# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200Classification(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, performed: bool=None, duration: int=None, _class: str=None):  # noqa: E501
        """InlineResponse200Classification - a model defined in Swagger

        :param performed: The performed of this InlineResponse200Classification.  # noqa: E501
        :type performed: bool
        :param duration: The duration of this InlineResponse200Classification.  # noqa: E501
        :type duration: int
        :param _class: The _class of this InlineResponse200Classification.  # noqa: E501
        :type _class: str
        """
        self.swagger_types = {
            'performed': bool,
            'duration': int,
            '_class': str
        }

        self.attribute_map = {
            'performed': 'performed',
            'duration': 'duration',
            '_class': 'class'
        }

        self._performed = performed
        self._duration = duration
        self.__class = _class

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Classification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_classification of this InlineResponse200Classification.  # noqa: E501
        :rtype: InlineResponse200Classification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def performed(self) -> bool:
        """Gets the performed of this InlineResponse200Classification.


        :return: The performed of this InlineResponse200Classification.
        :rtype: bool
        """
        return self._performed

    @performed.setter
    def performed(self, performed: bool):
        """Sets the performed of this InlineResponse200Classification.


        :param performed: The performed of this InlineResponse200Classification.
        :type performed: bool
        """

        self._performed = performed

    @property
    def duration(self) -> int:
        """Gets the duration of this InlineResponse200Classification.


        :return: The duration of this InlineResponse200Classification.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration: int):
        """Sets the duration of this InlineResponse200Classification.


        :param duration: The duration of this InlineResponse200Classification.
        :type duration: int
        """

        self._duration = duration

    @property
    def _class(self) -> str:
        """Gets the _class of this InlineResponse200Classification.


        :return: The _class of this InlineResponse200Classification.
        :rtype: str
        """
        return self.__class

    @_class.setter
    def _class(self, _class: str):
        """Sets the _class of this InlineResponse200Classification.


        :param _class: The _class of this InlineResponse200Classification.
        :type _class: str
        """

        self.__class = _class
